=== b-babicz/InternetTechnologies/LAB9/dane_ksiazek.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT książki (książka*)> 
<!ELEMENT tytuł (#PCDATA)> 
<!ELEMENT książka (tytuł, podtytuł?, autor*, wydawnictwo, datawydania, numerwydania, numerISBN))>
<!ELEMENT podtytuł (#PCDATA)>
<!ELEMENT autor (#PCDATA)> 
<!ELEMENT wydawnictwo (#PCDATA)> 
<!ELEMENT datawydania (#PCDATA)> 
<!ELEMENT numerwydania (#PCDATA)> 
<!ELEMENT numerISBN (#PCDATA)>

=== b-babicz/InternetTechnologies/LAB9/dane_ksiazek.xml
<?xml version="1.0" encoding="utf-8"?> 
<!DOCTYPE dane_ksiazek SYSTEM "dane_ksiazek.dtd"> 
<książki>

    <książka>
    <tytuł>Ferdydurke</tytuł>
    <autor>Witold Gombrowicz</autor>
    <wydawnictwo>Filia</wydawnictwo>
    <datawydania>2018-04-03</datawydania>
    <numerwydania>4</numerwydania>
    <numerISBN>566566556485446448</numerISBN>
    </książka>


</książki>
